#!/bin/sh
echo "Running ktlint check..."
OUTPUT="/tmp/ktlint-$(date +%s)"
./gradlew spotlessCheck > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 Ktlint failed                 "
  echo " Please fix the above issues before committing "
  echo " Run ./gradlew spotlessApply to fix issues.    "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT
